### ISSUE TITLE
Монтаж видео выступлений

### ISSUE THREAD

**Issue by EngineerSpock** [DotNetRu/Docs#4]
Многие видео, которые мы получаем от площадок - без монтажа. Это ведёт к проблемам, поскольку, например, слайды могут быть практически не видны (пример: https://youtu.be/fU5OF9nJayI)

Нужно либо искать энтузиаста из сообщества на монтаж, либо, при возможности, попросить спонсорской помощи (денежной) на найм монтажёра.

**Comment by kulakovt** [comment]
Я немного описал наши ожидания к монтажу в пункте [Характеристики видео записи](https://github.com/DotNetRu/Docs/blob/master/Regulations/Instruction%20to%20host.md#%D1%85%D0%B0%D1%80%D0%B0%D0%BA%D1%82%D0%B5%D1%80%D0%B8%D1%81%D1%82%D0%B8%D0%BA%D0%B8-%D0%B2%D0%B8%D0%B4%D0%B5%D0%BE-%D0%B7%D0%B0%D0%BF%D0%B8%D1%81%D0%B8).
